### ISSUE TITLE
Typing anything in editor generates error

### ISSUE THREAD

**Issue by Vishv07** [cdli-gh/uqnu#1]
![image](https://user-images.githubusercontent.com/37216460/111502576-f8c76680-876b-11eb-9c73-38316da1122e.png)

**Comment by khoidt** [comment]
@Vishv07, thanks for pointing this out, I'll add a patch soon. Generally, it has to do with new text creation workflow that is not there yet. Meanwhile, it is possible to open texts from files. You can try this one, for example - [texts_selection.txt](https://github.com/cdli-gh/uqnu/files/6163127/texts_selection.txt).

**Comment by Vishv07** [comment]
Works for file 👍
