### ISSUE TITLE
web page title

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/uqnu#11]
Can we change the title of the page? It would be great that it says where the app is hosted (cdli when on cdli) and the name of the app itself
![Screenshot 2021-11-04 at 11 40 42](https://user-images.githubusercontent.com/14226547/140307598-a1712c2d-4d7a-46e5-bab1-db1f404614ab.png)

**Comment by harshagrawal523** [comment]
Hi @epageperron ! Can I work on this issue?

**Comment by harshagrawal523** [comment]
Hi @epageperron , I generated a pull request relating to it on 
https://github.com/cdli-gh/uqnu/pull/12
