### ISSUE TITLE
loading Ur III Adab corpus generates error

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/uqnu#8]
![Screenshot 2021-11-03 at 21 59 34](https://user-images.githubusercontent.com/14226547/140199131-85ce354d-9210-4a7e-bbb6-d5cddbf39f03.png)

**Comment by khoidt** [comment]
Could you please attach the ATF file or a list of p-numbers for testing?

**Comment by epageperron** [comment]
Works now! I guess it was the problem with the server itself?? However warning and errors don't show on the text side ( for any text )
